#include "cpu/exec.h"
//arith.c
make_EHelper(sub);
make_EHelper(add);
make_EHelper(cmp);
make_EHelper(inc);
//cc.c
make_EHelper(setcc);
//control.c
make_EHelper(call);
make_EHelper(ret);
make_EHelper(jcc);
make_EHelper(jmp);
//data-mov.c
make_EHelper(push);
make_EHelper(pop);
make_EHelper(mov);
make_EHelper(lea);
make_EHelper(movzx);
make_EHelper(leave);
//logic.c
make_EHelper(test);
make_EHelper(xor);
make_EHelper(or);
make_EHelper(and);
make_EHelper(shl);
make_EHelper(sar);
make_EHelper(shr);
//prefix.c

//special.c
make_EHelper(operand_size);
make_EHelper(inv);
make_EHelper(nop);
//system.c
make_EHelper(nemu_trap);
